
-- INSERTAMOS INVENTARIO DE ALGUNOS LIBROS
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0001', 1, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0002', 1, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0004', 1, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0005', 2, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0006', 2, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0008', 2, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0010', 3, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0011', 3, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0012', 3, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0013', 3, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0014', 4, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0015', 4, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0016', 4, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0017', 5, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0019', 5, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0020', 6, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0022', 6, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0024', 6, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0026', 7, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0018', 7, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L0007', 8, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L897422', 8, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L395978', 9, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L226284', 9, 'D');
INSERT INTO public.inventories
(inventory_code, book_id, status)
VALUES('L089493', 10, 'D');
